version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: airtable-agenda_app
    restart: on-failure
    volumes:
      - .:/var/www

  web:
    image: nginx:1-alpine
    restart: on-failure
    container_name: airtable-agenda_web
    working_dir: /var/www
    links:
      - app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx

