FROM php:7.2-fpm-alpine

ENV HOST_USER 1000
ENV HOST_UID 1000

# Install PHP packages
RUN docker-php-ext-install \
    json

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www

COPY --chown=1000:1000 . .

RUN chmod -Rf 0664 cache
RUN chmod -Rf 0664 logs
